#### Server configurations ####
     # The maximum amount of days going to past will be crawled for the "Sendung Verpasst?" section.
    maximumDaysForSendungVerpasstSection: 6

    # The maximum amount of cpu threads to be used.
    maximumCpuThreads: 80

    # The maximum duration in minutes the server should run.<br>
    # If set to 0 the server runs without a time limit.
    maximumServerDurationInMinutes: 0
    
    # These Sender will NOT be crawled.
    # If no Sender are included the server will crawl all Sender but these.
    #senderExcluded:
    #  - ARD
    
    # If set only these Sender will be crawled all other will be ignored.
    #senderIncluded:
    # - ARD
    
    # The formats in which the filmlist should be saved to.
    # Possible are: JSON, OLD_JSON, JSON_COMPRESSED, OLD_JSON_COMPRESSED
    filmlistSaveFormats:
      - JSON
      - OLD_JSON
      - JSON_COMPRESSED
      - OLD_JSON_COMPRESSED
    
    # The paths where which filmlist should be safed to.
    filmlistSavePaths:
      JSON: ~/.mserver/filmlist/filmliste.json
      OLD_JSON: ~/.mserver/filmlist/filmliste_old.json
      JSON_COMPRESSED: ~/.mserver/filmlist/filmliste.json.xz
      OLD_JSON_COMPRESSED: ~/.mserver/filmlist/filmliste_old.json.xz
    
    # The format of the film list to import.
    # Possible are: JSON, OLD_JSON, JSON_COMPRESSED, OLD_JSON_COMPRESSED
    filmlistImportFormat: OLD_JSON_COMPRESSED
    
    # The path/URL of the film list to import.
    filmlistImportLocation: https://verteiler1.mediathekview.de/Filmliste-akt.xz

#### Default crawler configurations ####
     # The maximum amount of URLs to be processed per task.
    maximumUrlsPerTask: 50

     # The maximum duration in minutes a crawler may run.
    maximumCrawlDurationInMinutes: 30

     # The maximum amount of sub pages to be crawled.<br>
     # Example: If a Sendung overview side has 10 pages with videos for this Sendung and
     # the amount set by this is 5 then the crawler crawls pages 1 to 5.
    maximumSubpages: 3


#### Specific crawler configurations ####
#    senderConfigurations:
#      ARD:
        # The maximum amount of URLs to be processed per task.
#        maximumUrlsPerTask: 25
        # The maximum duration in minutes a crawler may run.
#          maximumCrawlDurationInMinutes: 30
        # The maximum amount of sub pages to be crawled.<br>
        # Example: If a Sendung overview side has 10 pages with videos for this Sendung and
        # the amount set by this is 5 then the crawler crawls pages 1 to 5.
#          maximumSubpages: 3